namespace CareerPath.Api.Models;

public enum ApplicationStatus
{
    Pending,
    Accepted,
    Rejected,
    Withdrawn,
}

public enum ApplicationOrigin
{
    /// <summary>The applicant answered a listing. The listing owner decides.</summary>
    Applied,

    /// <summary>The listing owner invited someone. That person decides.</summary>
    Invited,
}

public class Application
{
    public int Id { get; set; }
    public int ListingId { get; set; }
    public Listing Listing { get; set; } = null!;
    public int ApplicantId { get; set; }
    public User Applicant { get; set; } = null!;

    public ApplicationOrigin Origin { get; set; } = ApplicationOrigin.Applied;
    public required string Message { get; set; }
    public ApplicationStatus Status { get; set; } = ApplicationStatus.Pending;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? RespondedAt { get; set; }

    public AiReview? Review { get; set; }

    /// <summary>Who answers this request: the owner for applications, the invited person for invites.</summary>
    public int DeciderId => Origin == ApplicationOrigin.Applied ? Listing.OwnerId : ApplicantId;

    /// <summary>Who can take the request back before it is answered.</summary>
    public int SenderId => Origin == ApplicationOrigin.Applied ? ApplicantId : Listing.OwnerId;
}

/// <summary>
/// A written assessment of how well an applicant suits a listing. Generated by an LLM when one is
/// configured, otherwise by the rule-based writer in AiReviewService.
/// </summary>
public class AiReview
{
    public int Id { get; set; }
    public int ApplicationId { get; set; }
    public Application Application { get; set; } = null!;

    /// <summary>Serialised AiReviewContent.</summary>
    public required string ContentJson { get; set; }

    /// <summary>The model that wrote it, or "Rule-based" when no model was available.</summary>
    public required string Source { get; set; }

    public int MatchScore { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
}
